//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_cine_swcEntities : DbContext
    {
        public bd_cine_swcEntities()
            : base("name=bd_cine_swcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_censura> tb_censura { get; set; }
        public virtual DbSet<tb_DetalleVentaProducto> tb_DetalleVentaProducto { get; set; }
        public virtual DbSet<tb_empleado> tb_empleado { get; set; }
        public virtual DbSet<tb_estadoempleado> tb_estadoempleado { get; set; }
        public virtual DbSet<tb_funcion> tb_funcion { get; set; }
        public virtual DbSet<tb_genero> tb_genero { get; set; }
        public virtual DbSet<tb_pelicula> tb_pelicula { get; set; }
        public virtual DbSet<tb_producto> tb_producto { get; set; }
        public virtual DbSet<tb_sala> tb_sala { get; set; }
        public virtual DbSet<tb_Sexo> tb_Sexo { get; set; }
        public virtual DbSet<tb_tamaño> tb_tamaño { get; set; }
        public virtual DbSet<tb_tipoProducto> tb_tipoProducto { get; set; }
        public virtual DbSet<tb_tipotrabajador> tb_tipotrabajador { get; set; }
        public virtual DbSet<tb_VentaBoleto> tb_VentaBoleto { get; set; }
        public virtual DbSet<tb_VentaProducto> tb_VentaProducto { get; set; }
    }
}
