//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_funcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_funcion()
        {
            this.tb_VentaBoleto = new HashSet<tb_VentaBoleto>();
        }
    
        public int idFuncion { get; set; }
        public string nombre_funcion { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<int> nroSala { get; set; }
        public Nullable<System.TimeSpan> hora_funcion { get; set; }
        public Nullable<int> idPelicula { get; set; }
        public Nullable<int> idSala { get; set; }
    
        public virtual tb_pelicula tb_pelicula { get; set; }
        public virtual tb_sala tb_sala { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_VentaBoleto> tb_VentaBoleto { get; set; }
    }
}
